### ISSUE TITLE
submods crash the game

### ISSUE THREAD

**Issue by BrandiBlitz** [my-otter-self/otters-MAS-submods#1]
I tried all your submods and they bare crashing on version 0.12.8. please optimize the code for a better experience. thank you.

**Comment by dreamscached** [comment]
Please provide at least some details about it. Traceback, MAS logs, anything that can help fix the issue.

**Comment by my-otter-self** [comment]
they arent ready yet, im so sorry! i'll leave a disclaimer for that to avoid future mistakes. thank you for letting me know tho! have a great day~

**Comment by BrandiBlitz** [comment]
> they arent ready yet, im so sorry! i'll leave a disclaimer for that to avoid future mistakes. thank you for letting me know tho! have a great day~

anytime! the period submod is the one that hasn't crashed yet

**Comment by dreamscached** [comment]
> > they arent ready yet, im so sorry! i'll leave a disclaimer for that to avoid future mistakes. thank you for letting me know tho! have a great day~
> 
> anytime! the period submod is the one that hasn't crashed yet. you should delist your submods until they are ready.

This is a Git repository where submod development is in progress. It is solely up to author if they want the development to be public or not. If you have used *source* files (and not anything from [releases page](https://github.com/my-otter-self/otters-MAS-submods/releases)) — it's solely your fault as a user.

**Comment by BrandiBlitz** [comment]
> This is a Git repository where submod development is in progress. It is solely up to author if they want the development to be public or not. If you have used *source* files (and not anything from [releases page](https://github.com/my-otter-self/otters-MAS-submods/releases), which is empty at the moment) — it's solely your fault as a user.

Pardon my frankness; however, I would have never thought that caring for the DDLC modding community and looking after fellow modders/mod users would ever offend somone so deeply that they would go out of their way to mock someone for taking the risk and "taking one for the team". 

Regardless if you don't care who I am, It is okay to feel angry, but is never okay to take it out on someone. It's like throwing hot coal. The intent is to hurt someone, but in the end, your the one who gets burned.

Love how passionate you are about modding though~
